# ============================================================================
# SOURCE CONTENT — External references for requirement pedigree
# ============================================================================

sources:
  - id: src_design_doc
    name: Croatian App Design Document
    fileOrUrl: /home/ubuntu/.openclaw/workspace/croatian-app-design.md
    ownerRef: pkg_sources

  - id: src_srs_research
    name: SRS Algorithm Research
    fileOrUrl: https://en.wikipedia.org/wiki/Spaced_repetition
    ownerRef: pkg_sources

  - id: src_lasers_feelings
    name: Lasers & Feelings RPG System
    fileOrUrl: http://onesevendesign.com/lasers_and_feelings_rpg.pdf
    ownerRef: pkg_sources
